name: Greeting on variable day

on:
  push:
  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-20.04
    env:
      Greeting: Hello
    steps:
      - run: node --version
      - run: lsb_release -a
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: "Say Hello Mona it's Monday"
        run: echo "$env:Greeting $env:First_Name. Today is $env:DAY_OF_WEEK!"
        env:
          First_Name: Mona
      - run: echo %GITHUB_ACTOR%
